---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: gitlab_pre.yml
- include_tasks: gitlab_install.yml

- block: # Config GitLab
  - include_tasks: gitlab_search_config.yml
  - include_tasks: gitlab_post.yml
  tags:
    - gitlab-config
